// Domain types for KravConnect. The backend response shapes are inferred from
// the API contract; fields are kept optional where the server payload may vary.

export type Role = 'student' | 'teacher' | 'monitor'

export interface User {
  id: string | number
  name?: string
  username?: string
  email: string
  cpf?: string
  cep?: string
  role: Role
}

/** Response returned by POST /Auth */
export interface AuthResponse {
  token: string
  user?: User | null
}

/** Body sent to POST /Auth */
export interface LoginPayload {
  email: string
  password: string
}

/** Body sent to POST /users/registration */
export interface RegistrationPayload {
  name: string
  email: string
  password: string
  cpf: string
  cep: string
}

/** A gym (academia). Field names mirror the backend where known. */
export interface Gym {
  id: string | number
  name?: string
  cnpj?: string
  teacherName?: string
  /** Full street address, when provided at creation. */
  address?: string
  /** City line, e.g. "Santos · SP". */
  city?: string
  cep?: string
  /** Geocoded coordinates for the map + check-in geofence. */
  lat?: number
  lng?: number
}

/**
 * A class (aula) created by a teacher. The authoritative API has no
 * "list classes" GET endpoint, so created classes are cached locally to drive
 * the teacher's manager and the student's content view.
 */
export interface GymClass {
  id: string
  name: string
  /** Modality, e.g. "Krav Maga — Fundamentos". */
  modality?: string
  /** Schedule line, e.g. "Seg/Qua · 19:00". */
  schedule?: string
  /** Lesson notes / content blocks (POST /Gym/Classes/Information). */
  contents: string[]
  /** Video URLs (POST /Gym/Classes/Videos). */
  videos: string[]
  createdAt: string
}

/** Status of a generated invite link. */
export type InviteStatus = 'active' | 'used' | 'expired'

/** An invite link generated by a teacher (GET /Gym/Invite/Requests / list). */
export interface Invite {
  id: string | number
  token: string
  /** Full shareable URL, when the backend provides it. */
  url?: string
  status?: InviteStatus
  createdAt?: string
  expiresAt?: string
}

/** A pending join request from a student (GET /Gym/Invite/Requests). */
export interface InviteRequest {
  id_aluno: string | number
  name?: string
  cpf?: string
  cep?: string
  requestedAt?: string
  status?: 'pending' | 'approved' | 'refused'
}

/** Enrollment / payment health, when the backend reports it. */
export type StudentStatus = 'active' | 'late' | 'inactive'
export type PaymentStatus = 'paid' | 'pending' | 'late'

/**
 * A student enrolled in a gym (GET /Gym/Students/Select). Beyond the core
 * identity fields, every extra field is optional — they are rendered only when
 * the backend includes them in the Select payload (graceful for partial data).
 */
export interface Student {
  id_aluno: string | number
  name?: string
  email?: string
  cpf?: string
  cep?: string
  phone?: string
  /** Graduação / faixa, e.g. "Faixa Azul". */
  belt?: string
  status?: StudentStatus
  /** Mensalidade. */
  paymentStatus?: PaymentStatus
  /** Plano contratado, e.g. "Mensal". */
  plan?: string
  /** ISO date the student joined the gym. */
  joinedAt?: string
  /** ISO date of the last confirmed presence. */
  lastPresence?: string
  /** Confirmed presences in the current month. */
  attendanceMonth?: number
}
